config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    resources :location, only: [:create]
  end

  devise_for :users
  get 'position/getPosition', to: 'position#getPosition', as: 'get_position'
  get 'map/show', to: 'map#show', as: 'show_map'
  get 'position/save', to: 'position#save' 
  get 'position/index', to: 'position#index', as: 'index_position'

  root 'position#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create -> {self.token = generate_token}
  private
 
	def generate_token
	    loop do
	      token = SecureRandom.hex
	      return token unless User.exists?({token: token})
	    end
	end
end

app/controllers/api/location_controller.rb
class Api::LocationController < ApplicationController
  #skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  
  def create
    latitud = params[:lat]
    longitud = params[:lon]
    token = params[:token]
    user = params[:user]
    @position = Position.new(user: user,latitud: latitud, longitud: longitud)
    if (token == User.find(user).token) and @position.save
      render json: @position, status: :created
    else
      render json: @position.errors, status: :unprocessable_entity
    end
  end

  private

  def location_params
    params.require(:user, :token).permit(:lat, :lon)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate_user!
  
  def show
  	@results = Position.where({user: current_user.id})
  end
end

app/controllers/position_controller.rb
class PositionController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def getPosition
  	@positions = (Position.where({user: current_user.id}).reverse)[0,10]
  end

  def save
  	respond_to do |format|
	    latitud = params[:lat]
	    longitud = params[:lon]
	    @position = Position.new(user: current_user.id,latitud: latitud, longitud: longitud)
	    if @position.save
	          format.html { redirect_to get_position_path }
	    else
	        redirect_to get_position_path
	    end
	end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/position_helper.rb
module PositionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="mb-2">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= index_position_path %>">
            <img src="<%= asset_path 'trackerM.png'%>"  width="40" height="40" class="d-inline-block align-top" alt="">Tracker M
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#contenidoNavbar" aria-controls="contenidoNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <% if user_signed_in? then %>
            <div class="collapse navbar-collapse" id="contenidoNavbar">
              <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                  <a class="nav-link" href="<%= get_position_path %>"> Track me! </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="<%= show_map_path %>"> History </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#"> Close to me</a>
                </li>
              </ul>


              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

                   <%= current_user.email %> &nbsp
                  </a>  
                  <div class="dropdown-menu">
                    <%= link_to "Mi Perfil", '#', class:"dropdown-item", :remote=>true %>
                    <%= link_to "Salir", destroy_user_session_path, :method=>:delete, class:"dropdown-item"%>
                  </div>
                </li>
              </ul>

              <p>&nbsp&nbsp&nbsp&nbsp</p>
            </div>
          <% end %>
        </div>
      </nav>  
    </header>  

    <%= yield %>

  </body>
</html>

app/views/map/show.html.erb
<h1>Map#show</h1>
<p>Find me in app/views/map/show.html.erb</p>
<br>
<div id="map"></div>
<script>
  	function initMap(){
	    var positions = <%= raw @results.to_json %>;
	    var centroMap;
	    if(positions[0]!=null){
	      centroMap  = new google.maps.LatLng(positions[0].latitud,positions[0].longitud);
	    }else{
	      centroMap = new google.maps.LatLng(6.217, -75.567);
	    }
	    var options = {
	      zoom: 16,
	      center: centroMap
	    };
	    var myMap = new google.maps.Map(document.getElementById("map"), options);
	    var i;
	    for(i=0; i<positions.length; i++){
	      var pos = new google.maps.LatLng(positions[i].latitud, positions[i].longitud);
	      var mark = new google.maps.Marker({
	        position: pos,
	        map: myMap
	      });
	    }
  	}
</script>
<script 
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCe0d0tWZ9ErIv3r1YfnudfgyObTkL9DzM&callback=initMap" async defer> 
    </script>

app/views/position/getPosition.html.erb
<h1>Position</h1>

<script>
	function getLocation() {
	    if (navigator.geolocation) {
	        navigator.geolocation.getCurrentPosition(storePosition);
	    } else {
	        document.write("Geolocation is not supported by this browser.");
	    }
	}

	function showPosition(position) {
	    document.write("<br> Latitude: " + position.coords.latitude +
	    " Longitude: " + position.coords.longitude);
	}

	function sendPosition(position) {
		window.open("save?lat="+position.coords.latitude +"&lon="+position.coords.longitude,"_self");
	}

	function storePosition(position){
        
        var original_url = window.location.href;
        var store_url = "save?lat=" + position.coords.latitude +
		"&lon=" + position.coords.longitude;
        var url = original_url.slice(0,original_url.indexOf("getPosition")) + store_url;
	window.open(url, "_self");
  
}

	setInterval(getLocation,1000);
</script>	


<% while !@positions.empty? %>
    <% coordinate = @positions.pop %>
    <ul>
    	<li> <b>UserId:</b> <%= current_user.email %></li>
    	<li> <b>Latitude:</b> <%= coordinate.latitud %></li>
    	<li> <b>Longitude:</b> <%= coordinate.longitud %></li>
    </ul>
<% end %>

app/views/position/index.html.erb
<h3>Bienvenido</h3>